// Next.js
import type { Metadata } from "next";
import { Inter, Barlow } from "next/font/google";
import { ThemeProvider } from "next-themes";

// Global CSS
import "./globals.css";
// import { ThemeProvider } from "next-themes";

// Fonts
const InterFont = Inter({ subsets: ["latin"] });
const barlowFont = Barlow({
  subsets: ["latin"],
  weight: ["500", "700"],
  variable: "--font-barlow",
});

export const metadata: Metadata = {
  title: "GoShop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      {/* <html lang="en" suppressHydrationWarning></html> */}
      <body className={`${InterFont.className} ${barlowFont.variable}`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="default"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
